version: '3.4'
services:
  test-api:
    build: .
    container_name: test-api 
    image: test-api
    stop_signal: SIGINT
    restart: always
    ports:
      - "3100:3100"
    env_file:
      - .env
    depends_on:
      - test-mysql
    volumes:
      - .:/src/app
      - /src/app/node_modules
    networks: 
        - net_test

  test-mysql:
    image: mysql/mysql-server:5.7
    container_name: test-mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    networks: 
        - net_test
networks:
  net_test:
    driver: bridge